FROM phusion/baseimage:0.9.16

MAINTAINER George Vagenas - gvagenas@telestax.com

RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
RUN locale-gen en_US en_US.UTF-8 && dpkg-reconfigure locales

RUN apt-get update

RUN apt-get install -y screen wget ipcalc unzip && apt-get install -y openjdk-7-jdk
